### ISSUE TITLE
Package.swift references Kitura-CredentialsFacebook

### ISSUE THREAD

**Issue by ianpartridge** [lluisgerard/Kitura-CredentialsSlack#1]

**Comment by lluisgerard** [comment]
Thanks for the heads up! I wonder why the example tests I did with both Facebook and Slack libraries didn't complain.

I'll take a look on how to contribute to https://github.com/IBM-Swift/Kitura-Credentials-Sample with this library (not being from IBM). Also I was thinking that there is a lot of repetition happening inside every `CredentialsPluginProtocol` class (Google, Facebook, etc) maybe this can be simplified.

**Comment by ianpartridge** [comment]
Hi, it's great to see your library.

If you have suggestions on the overall Kitura-Credentials architecture the team would be very interested. Please open Issues/PRs and we can discuss 😃
